batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/classes/BatchApexJobHelper.cls
public with sharing class BatchApexJobHelper {
    public static BatchApexJobHelper instance;

    public static BatchApexJobHelper getInstance() {
        if (instance == null) {
            instance = new BatchApexJobHelper();
        }
        return instance;
    }

    public BatchApexJobHelper() {
    }

    public void verifyBatchJob(Batch_Apex_Job__c apexJob) {
        String batchJobName = apexJob.Batch_Class_Name__c;
        try {
            BatchJobBase apexJobTypeCast = (BatchJobBase) Type.forName(batchJobName).newInstance();
        } catch (Exception e) {
            String errorMessage = 'Unable to create BatchJobBase instance from Batch Job {0}. Please make sure to type the correct name and ensure that it extends BatchJobBase.';
            apexJob.addError(String.format(errorMessage, new List<String>{ batchJobName }));
        }
    }
}