batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Job__c/recordTypes/Batchable.recordType-meta.xml
<RecordType>
    <fullName>Batchable</fullName>
    <active>true</active>
    <label>Batchable</label>
</RecordType>

force-app/main/default/objects/Batch_Apex_Job__c/recordTypes/Queueable.recordType-meta.xml
<RecordType>
    <fullName>Queueable</fullName>
    <active>true</active>
    <label>Queueable</label>
</RecordType>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Schedule__c/recordTypes/Custom_Cron_Expression_Job.recordType-meta.xml
<RecordType>
    <fullName>Custom_Cron_Expression_Job</fullName>
    <active>true</active>
    <description>Jobs with custom cron expression</description>
    <label>Custom Cron Expression Job</label>
</RecordType>

force-app/main/default/objects/Batch_Job_Schedule__c/recordTypes/Daily_Job.recordType-meta.xml
<RecordType>
    <fullName>Daily_Job</fullName>
    <active>true</active>
    <description>Daily batch jobs</description>
    <label>Daily Job</label>
</RecordType>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Job_Schedule__c/recordTypes/Existing_Scheduled_Job.recordType-meta.xml
<RecordType>
    <fullName>Existing_Scheduled_Job</fullName>
    <active>true</active>
    <description>Link an existing Scheduled Apex job</description>
    <label>Existing Scheduled Job</label>
</RecordType>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/recordTypes/Hourly_Job.recordType-meta.xml
<RecordType>
    <fullName>Hourly_Job</fullName>
    <active>true</active>
    <description>Hourly batch jobs</description>
    <label>Hourly Job</label>
</RecordType>

force-app/main/default/objects/Batch_Job_Schedule__c/recordTypes/Monthly_Job.recordType-meta.xml
<RecordType>
    <fullName>Monthly_Job</fullName>
    <active>true</active>
    <description>Monthly batch jobs</description>
    <label>Monthly Job</label>
</RecordType>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/recordTypes/Weekly_Job.recordType-meta.xml
<RecordType>
    <fullName>Weekly_Job</fullName>
    <active>true</active>
    <description>Weekly batch jobs</description>
    <label>Weekly Job</label>
</RecordType>

force-app/main/default/objects/Batch_Job_Schedule__c/recordTypes/Yearly_Job.recordType-meta.xml
<RecordType>
    <fullName>Yearly_Job</fullName>
    <active>true</active>
    <description>Yearly batch jobs</description>
    <label>Yearly Job</label>
</RecordType>

batch-scheduler-framework/main/batch-job-management/classes/RecordTypeCache.cls
public inherited sharing class RecordTypeCache {
    
    private static Map<String, Schema.RecordTypeInfo> rtInfosBatchJobSchedule = Schema.SObjectType.Batch_Job_Schedule__c.getRecordTypeInfosByDeveloperName();
    private static Map<String, Schema.RecordTypeInfo> rtInfosBatchJobApexJob = Schema.SObjectType.Batch_Apex_Job__c.getRecordTypeInfosByDeveloperName();
    public static final Id SCHEDULER_RECORD_TYPE_HOURLY_JOB  = rtInfosBatchJobSchedule.get('Hourly_Job').getRecordTypeId();
    public static final Id SCHEDULER_RECORD_TYPE_DAILY_JOB   = rtInfosBatchJobSchedule.get('Daily_Job').getRecordTypeId();
    public static final Id SCHEDULER_RECORD_TYPE_WEEKLY_JOB  = rtInfosBatchJobSchedule.get('Weekly_Job').getRecordTypeId();
    public static final Id SCHEDULER_RECORD_TYPE_MONTHLY_JOB = rtInfosBatchJobSchedule.get('Monthly_Job').getRecordTypeId();
    public static final Id SCHEDULER_RECORD_TYPE_YEARLY_JOB  = rtInfosBatchJobSchedule.get('Yearly_Job').getRecordTypeId();
    public static final Id SCHEDULER_RECORD_TYPE_CUSTOM_CRON_EXPRESSION_JOB = rtInfosBatchJobSchedule.get('Custom_Cron_Expression_Job').getRecordTypeId();
    public static final Id SCHEDULER_RECORD_TYPE_EXISTING_SCHEDULED_JOB_JOB = rtInfosBatchJobSchedule.get('Existing_Scheduled_Job').getRecordTypeId();
    public static final Id JOB_RECORD_TYPE_BATCHABLE = rtInfosBatchJobApexJob.get('Batchable').getRecordTypeId();
    public static final Id JOB_RECORD_TYPE_QUEUEABLE = rtInfosBatchJobApexJob.get('Queueable').getRecordTypeId();
    

}