batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/Batch_Job_Log__c.object-meta.xml
<CustomObject>
    <description>Apex Batch Job Log</description>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Apex_Job__c.field-meta.xml
<CustomField>
    <fullName>Batch_Apex_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Apex Job</label>
    <referenceTo>Batch_Apex_Job__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Name__c</fullName>
    <description>Apex Batch Job class name</description>
    <label>Batch Job Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/BatchApexJobParent__c.field-meta.xml
<CustomField>
    <fullName>BatchApexJobParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Apex Job (Parent)</label>
    <referenceTo>Batch_Apex_Job__c</referenceTo>
    <relationshipLabel>Parent Apex Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batches_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batches_Processed__c</fullName>
    <label>Batches Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/BatchJobScheduleParent__c.field-meta.xml
<CustomField>
    <fullName>BatchJobScheduleParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Job Schedule (Parent)</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Job Logs (Batch Job Schedule (Parent))</relationshipLabel>
    <relationshipName>Batch_Job_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <description>Batch job completed time</description>
    <label>Completed Date</label>
    <type>DateTime</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Execution_Result__c.field-meta.xml
<CustomField>
    <fullName>Execution_Result__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Number_of_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Errors__c</fullName>
    <label>Number of Errors</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Information</fullName>
                <label>ℹ️ Information</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>✔️ Success</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>⛔ Error</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <label>⛔ Failed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>✔️ Completed</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>⏳ Processing</label>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
                <label>⚠️ Completed with Errors</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/BatchApexStatusEvent__e/BatchApexStatusEvent__e.object-meta.xml
<CustomObject>
    <label>Batch Apex Status Event</label>
    <pluralLabel>Batch Apex Status Events</pluralLabel>
</CustomObject>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/classes/BatchJobLogger.cls
/**
 * This class is part of the sfdx-batch-orchestrator package, released under the MIT license.
 *
 * @description       : Logger Class to bundle creation of Log Events
 * @author            : dschibster
 * @group             : Scheduler
 * @last modified on  : 2021-08-27
 * @last modified by  : dschibster
 **/

public with sharing class BatchJobLogger {
    public static void log(List<SObject> chunkScope, Id asyncJobId, String status, String message, String context) {
        String scopeJSON = chunkScope != null ? JSON.serializePretty(chunkScope).left(129999) : '';
        BatchApexStatusEvent__e statusEvent = new BatchApexStatusEventBuilder()
            .withContext(context)
            .withStatus(status)
            .withMessage(message)
            .withScope(scopeJSON)
            .withTimestamp(DateTime.now().getTime())
            .withJobId(asyncJobId)
            .withLimits()
            .getRecord();

        EventBus.publish(statusEvent);
    }

    public static void logStart(String className, Id asyncJobId, Id scheduleId, Id jobId) {
        writeParentLog(className, asyncJobId, scheduleId, jobId);
        log(null, asyncJobId, 'Information', 'Batch Job started', 'START');
    }

    public static void logStartAfterParent(Id asyncJobId, String message) {
        log(null, asyncJobId, 'Information', message, 'START');
    }

    public static void logFinish(Id asyncJobId) {
        log(null, asyncJobId, 'Information', 'Batch Job finished', 'FINISH');
    }

    public static void logFinish(Id asyncJobId, String message) {
        log(null, asyncJobId, 'Information', message, 'FINISH');
    }

    public static void logExecute(List<SObject> chunkScope, Id asyncJobId, String status) {
        log(chunkScope, asyncJobId, status, null, 'EXECUTE');
    }

    public static void logExecuteInformation(Id asyncJobId, String message) {
        log(null, asyncJobId, 'Information', message, 'EXECUTE');
    }

    public static void logExecuteInformation(List<SObject> scope, Id asyncJobId, String message) {
        log(scope, asyncJobId, 'Information', message, 'EXECUTE');
    }

    public static void logExecute(List<SObject> chunkScope, Id asyncJobId, String status, String message) {
        log(chunkScope, asyncJobId, status, message, 'EXECUTE');
    }

    private static Batch_Job_Log__c getParentLog(String className, Id asyncJobId, Id scheduleId, Id jobId) {
        return new Batch_Job_Log__c(
            Batch_Job_Name__c = className,
            Batch_Apex_Job__c = jobId,
            Batch_Job_Schedule__c = scheduleId,
            BatchApexJobParent__c = jobId,
            BatchJobScheduleParent__c = scheduleId,
            AsyncApexJobId__c = asyncJobId,
            RecordTypeId = RecordTypeCache.LOG_RECORD_TYPE_PARENT,
            Result__c = 'Processing'
        );
    }

    public static void writeParentLog(String className, Id asyncJobId, Id scheduleId, Id jobId, Boolean isAsync) {
        Batch_Job_Log__c parentLog = getParentLog(className, asyncJobId, scheduleId, jobId);
        if (isAsync) {
            EventBus.publish(new BatchApexStatusEventBuilder().withSObjectJSON(JSON.serializePretty(parentLog)).getRecord());
        } else {
            insert parentLog;
        }
    }

    public static void writeParentLog(String className, Id asyncJobId, Id scheduleId, Id jobId) {
        writeParentLog(className, asyncJobId, scheduleId, jobId, false);
    }

    public static void writeQueueableParentLog(String className, Id asyncJobId, Id scheduleId, Id jobId) {
        Batch_Job_Log__c queueableLog = getParentLog(className, asyncJobId, scheduleId, jobId);
        queueableLog.RecordTypeId = RecordTypeCache.LOG_RECORD_TYPE_QUEUEABLE;
        EventBus.publish(new BatchApexStatusEventBuilder().withSObjectJSON(JSON.serializePretty(queueableLog)).getRecord());
    }

    public static void updateParentQueueableLog(Id asyncJobId) {
        AsyncApexJob job = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CompletedDate, CreatedBy.Email, ExtendedStatus
            FROM AsyncApexJob
            WHERE Id = :asyncJobId
        ];

        Datetime completedDate = job.CompletedDate;
        if (completedDate == null) {
            completedDate = Datetime.now();
        }

        BatchApexStatusEvent__e statusEvent = new BatchApexStatusEventBuilder()
            .withContext('FINISH')
            .withStatus(job.Status)
            .withMessage(job.ExtendedStatus)
            .withTimestamp(completedDate.getTime())
            .withJobId(asyncJobId)
            .getRecord();

        EventBus.publish(statusEvent);
    }

    /**
     * Copyright (c) Ian Huang Salesforce
     *
     * Permission is hereby granted, free of charge, to any person obtaining a copy
     * of this software and associated documentation files (the "Software"), to deal
     * in the Software without restriction, including without limitation the rights
     * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
     * copies of the Software, and to permit persons to whom the Software is
     * furnished to do so, subject to the following conditions:
     * The above copyright notice and this permission notice shall be included in all
     * copies or substantial portions of the Software.
     *
     * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
     * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
     * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
     * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
     * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
     * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
     * OR OTHER DEALINGS IN THE SOFTWARE.
     */

    public static void logLegacy(String batchJobName, Id asyncJobId, Id scheduleId, Id jobId) {
        logLegacy(batchJobName, asyncJobId, '', scheduleId, jobId);
    }

    //Log batch job exection result
    public static void logLegacy(String batchJobName, Id asyncJobId, String summary, Id scheduleId, Id jobId) {
        AsyncApexJob job = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CompletedDate, CreatedBy.Email, ExtendedStatus
            FROM AsyncApexJob
            WHERE Id = :asyncJobId
        ];

        String executeResult = job.ExtendedStatus;

        // Create a batch job log record to notify the batch job execute result
        try {
            Batch_Job_Log__c bjl = new Batch_Job_Log__c(
                Batch_Job_Name__c = batchJobName,
                Batch_Apex_Job__c = jobId,
                Batch_Job_Schedule__c = scheduleId,
                BatchApexJobParent__c = jobId,
                BatchJobScheduleParent__c = scheduleId,
                Completed_Date__c = job.CompletedDate,
                Result__c = job.Status,
                Batches_Processed__c = job.JobItemsProcessed,
                Number_of_Errors__c = job.NumberOfErrors,
                RecordTypeId = RecordTypeCache.LOG_RECORD_TYPE_LEGACY,
                Execution_Result__c = (String.isNotBlank(executeResult) ? executeResult : '') + (String.isNotBlank(summary) ? '\n' + summary : '')
            );
            insert bjl;
        } catch (Exception ex) {
            throw new DmlException('Failed to save batch job log: ' + ex.getMessage());
        }
    }
}