batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Group__c.field-meta.xml
<CustomField>
    <fullName>Batch_Group__c</fullName>
    <description>Group of batch jobs running together</description>
    <inlineHelpText>Group of batch jobs</inlineHelpText>
    <label>Batch Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Job__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the Batch Apex job will be executed</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Job__c/recordTypes/Batchable.recordType-meta.xml
<RecordType>
    <fullName>Batchable</fullName>
    <active>true</active>
    <label>Batchable</label>
</RecordType>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Job_Log__c/Batch_Job_Log__c.object-meta.xml
<CustomObject>
    <description>Apex Batch Job Log</description>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Apex_Job__c.field-meta.xml
<CustomField>
    <fullName>Batch_Apex_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Apex Job</label>
    <referenceTo>Batch_Apex_Job__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/fields/Cron_Trigger_Id__c.field-meta.xml
<CustomField>
    <fullName>Cron_Trigger_Id__c</fullName>
    <description>Scheduled Job Cron Trigger Id</description>
    <inlineHelpText>Scheduled Job Cron Trigger Id</inlineHelpText>
    <label>Cron Trigger Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-scheduler-framework/test/batch-job-scheduler/classes/BatchJobSchedulerTest.cls
/*
Copyright (c) Ian Huang Salesforce

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
OR OTHER DEALINGS IN THE SOFTWARE.
*/

@isTest
public class BatchJobSchedulerTest {
    @testSetup
    static void setup() {
        BatchJobSchedulerTestDataFactory.createBatchSchedulerContext();
    }

    @isTest
    static void testExecute() {
        Id cronTriggerId = System.schedule('test job.schedule.Name', '0 3 4 5 1/3 ? *', new BatchJobScheduler());

        Batch_Job_Schedule__c sched = [SELECT Id FROM Batch_Job_Schedule__c LIMIT 1];
        sched.Cron_Trigger_Id__c = cronTriggerId;
        update sched;

        BatchJobScheduler batchJobScheduler = new BatchJobScheduler();
        batchJobScheduler.run(cronTriggerId);

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('_BJS_Testing_', accounts[0].Type);
        System.assertEquals('_BJS_Testing_', accounts[1].Type);
        System.assertEquals('_BJS_Testing_', accounts[2].Type);
    }

    @isTest
    static void testExecuteNext() {
        Id cronTriggerId = System.schedule('test job.schedule.Name', '0 3 4 5 1/3 ? *', new BatchJobScheduler());
        
        Batch_Job_Schedule__c sched = [SELECT Id FROM Batch_Job_Schedule__c LIMIT 1];
        sched.Cron_Trigger_Id__c = cronTriggerId;
        update sched;

        BatchJobScheduler batchJobScheduler = new BatchJobScheduler();
        batchJobScheduler.run(cronTriggerId);
        batchJobScheduler.executeNextJob();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('_BJS_Testing_', accounts[0].Type);
        System.assertEquals('_BJS_Testing_', accounts[1].Type);
        System.assertEquals('_BJS_Testing_', accounts[2].Type);
    }

    @isTest static void testConstructionOfJobMap(){
        Id cronTriggerId = System.schedule('test job.schedule.Name', '0 3 4 5 1/3 ? *', new BatchJobScheduler());
        

        Batch_Job_Schedule__c sched = [SELECT Id FROM Batch_Job_Schedule__c LIMIT 1];
        sched.Cron_Trigger_Id__c = cronTriggerId;
        update sched;

        List<Batch_Apex_Job__c> batchJobs = new List<Batch_Apex_Job__c>();
        for(Batch_Apex_Job__c qAble : [SELECT Id FROM Batch_Apex_Job__c WHERE Batch_Group__c = '2']){
            qAble.Enabled__c = false;
            batchJobs.add(qAble);
        }
        
        Batch_Apex_Job__c qAbleNewGroup = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = sched.Id,
            Batch_Class_Name__c = 'testqueueable',
            Batch_Group__c = '3',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_QUEUEABLE
        );
        batchJobs.add(qAbleNewGroup);
        upsert batchJobs;

        
        //Expected: isEnabledMap has indices from 1 to 3, batchJobs Map only has values for 1 and 3

        BatchJobScheduler batchJobScheduler = new BatchJobScheduler();
        batchJobScheduler.batchJobs = batchJobScheduler.loadActiveBatchJobs(cronTriggerId);
        System.assertEquals(new Set<Integer>(new List<Integer>{1,2,3}), batchJobScheduler.isEnabledMap.keySet());
        System.assert(batchJobScheduler.isEnabledMap.get(1), 'Batch Jobs in Group 1 were seen as disabled');
        System.assert(!batchJobScheduler.isEnabledMap.get(2), 'Batch Jobs in Group 2 were seen as enabled');
        System.assert(batchJobScheduler.isEnabledMap.get(3), 'Batch Jobs in Group 3 were seen as disabled');
        System.assert(batchJobScheduler.batchJobs.containsKey('1'), 'Batch Jobs in Group 1 were not found');
        System.assert(!batchJobScheduler.batchJobs.containsKey('2'), 'Batch Jobs in Group 2 were found');
        System.assert(batchJobScheduler.batchJobs.containsKey('3'), 'Batch Jobs in Group 3 were not found');

    }

    @isTest
    static void testExecuteNextSkipIndex() {
        Id cronTriggerId = System.schedule('test job.schedule.Name', '0 3 4 5 1/3 ? *', new BatchJobScheduler());
        

        Batch_Job_Schedule__c sched = [SELECT Id FROM Batch_Job_Schedule__c LIMIT 1];
        sched.Cron_Trigger_Id__c = cronTriggerId;
        update sched;

        List<Batch_Apex_Job__c> batchJobs = new List<Batch_Apex_Job__c>();
        for(Batch_Apex_Job__c qAble : [SELECT Id FROM Batch_Apex_Job__c WHERE Batch_Group__c = '2']){
            qAble.Enabled__c = false;
            batchJobs.add(qAble);
        }
        
        Batch_Apex_Job__c qAbleNewGroup = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = sched.Id,
            Batch_Class_Name__c = 'testqueueable',
            Batch_Group__c = '3',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_QUEUEABLE
        );
        batchJobs.add(qAbleNewGroup);
        upsert batchJobs;

        BatchJobScheduler batchJobScheduler = new BatchJobScheduler();
        batchJobScheduler.run(cronTriggerId);
        batchJobScheduler.executeNextJob();

        System.assertEquals(3,batchJobScheduler.index, 'Disabled index 2 was not skipped');
        System.assert(!batchJobScheduler.batchJobs.containsKey('2'));
    }

    @isTest
    static void testlogBatchJob() {
        BatchJobHelper.logBatchJob('batchJobName', System.now(), 'errorMessages');

        List<Batch_Job_Log__c> logs = [SELECT Id FROM Batch_Job_Log__c];
        System.assertEquals(1, logs.size());
    }

    @isTest
    static void testBatchJob1() {
        BatchJobBase testBatchJob1 = (BatchJobBase) new TestBatchJob1();
        testBatchJob1.jobType = 'Batchable';
        Test.startTest();
        testBatchJob1.enqueue(100);
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('Prospect', accounts[0].Type);
        System.assertEquals('Prospect', accounts[1].Type);
        System.assertEquals('Prospect', accounts[2].Type);
    }

    @isTest
    static void testBatchJob2() {
        BatchJobBase testBatchJob2 = (BatchJobBase) new TestBatchJob2();
        testBatchJob2.jobType = 'Batchable';
        Test.startTest();
        testBatchJob2.enqueue(100);
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('Prospect', accounts[0].Type);
        System.assertEquals('Prospect', accounts[1].Type);
        System.assertEquals('Prospect', accounts[2].Type);
    }

    @isTest
    static void testBatchJob3() {
        BatchJobBase testBatchJob3 = (BatchJobBase) new TestBatchJob3();
        testBatchJob3.jobType = 'Batchable';
        Test.startTest();
        testBatchJob3.enqueue(100);
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('Prospect', accounts[0].Type);
        System.assertEquals('Prospect', accounts[1].Type);
        System.assertEquals('Prospect', accounts[2].Type);
    }
}