batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Group__c.field-meta.xml
<CustomField>
    <fullName>Batch_Group__c</fullName>
    <description>Group of batch jobs running together</description>
    <inlineHelpText>Group of batch jobs</inlineHelpText>
    <label>Batch Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Batch Apex job batch size, value between 1 to 2000.</description>
    <inlineHelpText>Value between 1 to 2000</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/EnhancedLogging__c.field-meta.xml
<CustomField>
    <fullName>EnhancedLogging__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText
    >Enhanced Logging requires additional methods to be used and is recommended to be done with all Jobs of one schedule. Please refer to the README for more information.</inlineHelpText>
    <label>Enhanced Logging</label>
    <type>Checkbox</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/test/batch-job-scheduler/classes/BatchOrchestratorTest.cls
/**
 * This class is part of the sfdx-batch-orchestrator package, released under the MIT license.
 *
 * @description       : Test Class that verifies the ad-hoc runs of Schedules and Batch Jobs
 * @author            : dschibster
 * @group             : Batch Job Management
 * @last modified on  : 2022-01-15
 * @last modified by  : dschibster
 **/

@isTest
public with sharing class BatchOrchestratorTest {
    @TestSetup
    static void makeData() {
        BatchJobSchedulerTestDataFactory.createBatchSchedulerContext();
    }

    @isTest
    static void confirmApexJobRunWithObject() {
        Batch_Apex_Job__c firstJob = [
            SELECT Id, Batch_Class_Name__c, Batch_Job_Schedule__c, Batch_Size__c, RecordType.DeveloperName, EnhancedLogging__c
            FROM Batch_Apex_Job__c
            WHERE Batch_Group__c = '1'
            LIMIT 1
        ];

        Test.startTest();
        BatchOrchestrator.runBatchJob(firstJob);
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];

        System.assertEquals(3, accounts.size(), 'The Account were not found');
        System.assertEquals('Prospect', accounts[0].Type, 'The Type was not switched for Account 1');
        System.assertEquals('Prospect', accounts[1].Type, 'The Type was not switched for Account 2');
        System.assertEquals('Prospect', accounts[2].Type, 'The Type was not switched for Account 3');
    }

    @isTest
    static void confirmApexJobRunWithId() {
        Batch_Apex_Job__c firstJob = [
            SELECT Id, Batch_Class_Name__c, Batch_Job_Schedule__c, Batch_Size__c, RecordType.DeveloperName, EnhancedLogging__c
            FROM Batch_Apex_Job__c
            WHERE Batch_Group__c = '1'
            LIMIT 1
        ];

        Test.startTest();
        BatchOrchestrator.runBatchJob(firstJob.Id);
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];

        System.assertEquals(3, accounts.size(), 'The Account were not found');
        System.assertEquals('Prospect', accounts[0].Type, 'The Type was not switched for Account 1');
        System.assertEquals('Prospect', accounts[1].Type, 'The Type was not switched for Account 2');
        System.assertEquals('Prospect', accounts[2].Type, 'The Type was not switched for Account 3');
    }

    @isTest
    static void confirmScheduleRun() {
        List<Batch_Apex_Job__c> jobsToNotRun = [
            SELECT Id, Batch_Class_Name__c, Batch_Job_Schedule__c, Batch_Size__c, RecordType.DeveloperName, EnhancedLogging__c
            FROM Batch_Apex_Job__c
            WHERE Batch_Group__c = '2'
        ];
        delete jobsToNotRun;

        Batch_Job_Schedule__c sched = [SELECT Id FROM Batch_Job_Schedule__c LIMIT 1];

        Test.startTest();
        BatchOrchestrator.runBatchSchedule(sched.Id);
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];

        System.assertEquals(3, accounts.size(), 'The Account were not found');
        System.assertEquals('Prospect', accounts[0].Type, 'The Type was not switched for Account 1');
        System.assertEquals('Prospect', accounts[1].Type, 'The Type was not switched for Account 2');
        System.assertEquals('Prospect', accounts[2].Type, 'The Type was not switched for Account 3');
    }
}