batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Group__c.field-meta.xml
<CustomField>
    <fullName>Batch_Group__c</fullName>
    <description>Group of batch jobs running together</description>
    <inlineHelpText>Group of batch jobs</inlineHelpText>
    <label>Batch Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Job__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the Batch Apex job will be executed</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/fields/Every_Number_of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Every_Number_of_Hours__c</fullName>
    <label>Every Number of Hour(s)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/fields/Preferred_Start_Hour__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Start_Hour__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Preferred Start Hour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0AM</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1AM</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2AM</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3AM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4AM</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5AM</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6AM</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7AM</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8AM</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10AM</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11AM</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12PM</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13PM</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14PM</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15PM</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>16PM</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>17PM</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>18PM</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19PM</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20PM</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>21PM</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22PM</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/fields/Preferred_Start_Minute__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Start_Minute__c</fullName>
    <label>Preferred Start Minute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/fields/Preferred_Start_Week_Day__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Start_Week_Day__c</fullName>
    <label>Preferred Start Week Day</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MON</fullName>
                <label>Monday</label>
            </value>
            <value>
                <fullName>TUE</fullName>
                <label>Tuesday</label>
            </value>
            <value>
                <fullName>WED</fullName>
                <label>Wednesday</label>
            </value>
            <value>
                <fullName>THU</fullName>
                <label>Thursday</label>
            </value>
            <value>
                <fullName>FRI</fullName>
                <label>Friday</label>
            </value>
            <value>
                <fullName>SAT</fullName>
                <label>Saturday</label>
            </value>
            <value>
                <fullName>SUN</fullName>
                <label>Sunday</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/test/batch-job-management/classes/BatchJobSchedulerTestDataFactory.cls
/**
 * This class is part of the sfdx-batch-orchestrator package, released under the MIT license.
 *
 * @description       : Test Data Factory to create the correct Data for Test Cases
 * @author            : dschibster
 * @group             : Batch Job Management
 * @last modified on  : 2021-08-27
 * @last modified by  : dschibster
 **/

@isTest
public with sharing class BatchJobSchedulerTestDataFactory {
    public static void createBatchSchedulerContext() {
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = RecordTypeCache.SCHEDULER_RECORD_TYPE_HOURLY_JOB;
        sch.Name = 'Test Hourly Name 001';
        sch.Every_Number_of_Hours__c = 1;
        sch.Preferred_Start_Minute__c = '0';
        insert sch;

        Batch_Apex_Job__c batchJob1 = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = sch.Id,
            Batch_Class_Name__c = 'TestBatchJob1',
            Batch_Group__c = '1',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_BATCHABLE
        );
        Batch_Apex_Job__c batchJob2 = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = sch.Id,
            Batch_Class_Name__c = 'TestBatchJob2',
            Batch_Group__c = '1',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_BATCHABLE
        );
        Batch_Apex_Job__c batchJob3 = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = sch.Id,
            Batch_Class_Name__c = 'TestBatchJob3',
            Batch_Group__c = '2',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_BATCHABLE
        );
        Batch_Apex_Job__c queueableJob1 = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = sch.Id,
            Batch_Class_Name__c = 'testqueueable',
            Batch_Group__c = '2',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_QUEUEABLE
        );

        insert new List<Batch_Apex_Job__c>{ batchJob1, batchJob2, batchJob3, queueableJob1 };

        Account account1 = new Account(Name = '__BatchJobSchedulerTest001', Type = '_BJS_Testing_');
        Account account2 = new Account(Name = '__BatchJobSchedulerTest002', Type = '_BJS_Testing_');
        Account account3 = new Account(Name = '__BatchJobSchedulerTest003', Type = '_BJS_Testing_');
        insert new List<Account>{ account1, account2, account3 };
    }

    public static Batch_Job_Schedule__c createWeeklyBatchJobSchedule() {
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = RecordTypeCache.SCHEDULER_RECORD_TYPE_WEEKLY_JOB;
        sch.Name = 'Test Weekly Name 001';
        sch.Preferred_Start_Week_Day__c = 'MON;TUE;WED';
        sch.Preferred_Start_Hour__c = '3';
        sch.Preferred_Start_Minute__c = '2';
        return sch;
    }

    public static Batch_Apex_Job__c createBatchJob(Batch_Job_Schedule__c schedule) {
        Batch_Apex_Job__c batchJob = new Batch_Apex_Job__c(
            Batch_Job_Schedule__c = schedule.Id,
            Batch_Class_Name__c = 'TestBatchJob1',
            Batch_Group__c = '1',
            Enabled__c = true,
            RecordTypeId = RecordTypeCache.JOB_RECORD_TYPE_BATCHABLE
        );
        return batchJob;
    }
}