batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/test/batch-job-scheduler/classes/BatchApexJobHandlerTest.cls
@isTest
public with sharing class BatchApexJobHandlerTest {
    @isTest
    static void shouldVerifyBeforeInsert() {
        Batch_Job_Schedule__c testSchedule = BatchJobSchedulerTestDataFactory.createWeeklyBatchJobSchedule();
        insert testSchedule;

        Test.startTest();
        Batch_Apex_Job__c testBatch = BatchJobSchedulerTestDataFactory.createBatchJob(testSchedule);
        testBatch.Batch_Class_Name__c = 'this_should_fail';
        Exception exceptionCaught;
        try {
            insert testBatch;
        } catch (Exception e) {
            exceptionCaught = e;
        }
        Test.stopTest();
        System.assert(exceptionCaught != null, 'The insertion of a false Batch Job was not prevented');
    }

    @isTest
    static void shouldVerifyBeforeUpdate() {
        Batch_Job_Schedule__c testSchedule = BatchJobSchedulerTestDataFactory.createWeeklyBatchJobSchedule();
        insert testSchedule;

        Test.startTest();
        Batch_Apex_Job__c testBatch = BatchJobSchedulerTestDataFactory.createBatchJob(testSchedule);
        testBatch.Batch_Class_Name__c = 'TestBatchJob1';
        insert testBatch;

        Exception exceptionCaught;
        try {
            testBatch.Batch_Class_Name__c = 'this_should_fail';
            update testBatch;
        } catch (Exception e) {
            exceptionCaught = e;
        }
        Test.stopTest();
        System.assert(exceptionCaught != null, 'The insertion of a false Batch Job was not prevented');
    }
}