batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/Batch_Job_Log__c.object-meta.xml
<CustomObject>
    <description>Apex Batch Job Log</description>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/AsyncApexCallsLimit__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexCallsLimit__c</fullName>
    <label>Async Apex Calls Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/AsyncApexCallsUsed__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexCallsUsed__c</fullName>
    <label>Async Apex Calls Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Apex_Job__c.field-meta.xml
<CustomField>
    <fullName>Batch_Apex_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Apex Job</label>
    <referenceTo>Batch_Apex_Job__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <description>Batch job completed time</description>
    <label>Completed Date</label>
    <type>DateTime</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/CPUTimeLimit__c.field-meta.xml
<CustomField>
    <fullName>CPUTimeLimit__c</fullName>
    <label>CPU Time Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/CPUTimeUsed__c.field-meta.xml
<CustomField>
    <fullName>CPUTimeUsed__c</fullName>
    <label>CPU Time Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/DMLRowsLimit__c.field-meta.xml
<CustomField>
    <fullName>DMLRowsLimit__c</fullName>
    <label>DML Rows Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/DMLRowsUsed__c.field-meta.xml
<CustomField>
    <fullName>DMLRowsUsed__c</fullName>
    <label>DML Rows Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/DMLStatementsLimit__c.field-meta.xml
<CustomField>
    <fullName>DMLStatementsLimit__c</fullName>
    <label>DML Statements Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/DMLStatementsUsed__c.field-meta.xml
<CustomField>
    <fullName>DMLStatementsUsed__c</fullName>
    <label>DML Statements Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Execution_Result__c.field-meta.xml
<CustomField>
    <fullName>Execution_Result__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/FailedBatches__c.field-meta.xml
<CustomField>
    <fullName>FailedBatches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Failed Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Parent_Log__c.field-meta.xml
<CustomField>
    <fullName>Parent_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Log</label>
    <referenceTo>Batch_Job_Log__c</referenceTo>
    <relationshipLabel>Batch Job Logs</relationshipLabel>
    <relationshipName>Child_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Information</fullName>
                <label>ℹ️ Information</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>✔️ Success</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>⛔ Error</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <label>⛔ Failed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>✔️ Completed</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>⏳ Processing</label>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
                <label>⚠️ Completed with Errors</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/SOQLQueriesLimit__c.field-meta.xml
<CustomField>
    <fullName>SOQLQueriesLimit__c</fullName>
    <label>SOQL Queries Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/SOQLQueriesUsed__c.field-meta.xml
<CustomField>
    <fullName>SOQLQueriesUsed__c</fullName>
    <label>SOQL Queries Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/SOQLRowsLimit__c.field-meta.xml
<CustomField>
    <fullName>SOQLRowsLimit__c</fullName>
    <label>SOQL Rows Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/SOQLRowsUsed__c.field-meta.xml
<CustomField>
    <fullName>SOQLRowsUsed__c</fullName>
    <label>SOQL Rows Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/SuccessfulBatches__c.field-meta.xml
<CustomField>
    <fullName>SuccessfulBatches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Successful Batches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/BatchApexStatusEvent__e/BatchApexStatusEvent__e.object-meta.xml
<CustomObject>
    <label>Batch Apex Status Event</label>
    <pluralLabel>Batch Apex Status Events</pluralLabel>
</CustomObject>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexCallsLimit__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexCallsUsed__c</fullName>
    <label>Async Apex Calls Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexCallsUsed__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexCallsLimit__c</fullName>
    <label>Async Apex Calls Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/CPUTimeLimit__c.field-meta.xml
<CustomField>
    <fullName>CPUTimeLimit__c</fullName>
    <label>CPU Time Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/DMLRowsLimit__c.field-meta.xml
<CustomField>
    <fullName>DMLRowsLimit__c</fullName>
    <label>DML Rows Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/DMLStatementsLimit__c.field-meta.xml
<CustomField>
    <fullName>DMLStatementsLimit__c</fullName>
    <label>DML Statements Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/SOQLQueriesLimit__c.field-meta.xml
<CustomField>
    <fullName>SOQLQueriesLimit__c</fullName>
    <label>SOQL Queries Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/SOQLQueriesUsed__c.field-meta.xml
<CustomField>
    <fullName>SOQLQueriesUsed__c</fullName>
    <label>SOQL Queries Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/classes/BatchApexStatusEventHelper.cls
public with sharing class BatchApexStatusEventHelper {
    List<BatchApexStatusEvent__e> triggerNew;
    Map<Id, AsyncApexJob> relevantApexJobs = new Map<Id, AsyncApexJob>();
    Map<Id, Batch_Job_Log__c> parentLogsByAsyncJobId = new Map<Id, Batch_Job_Log__c>();
    public Map<Id, Batch_Job_Log__c> parentLogsById = new Map<Id, Batch_Job_Log__c>();
    Set<Id> setFinishedParentLogs = new Set<Id>();

    public BatchApexStatusEventHelper(List<BatchApexStatusEvent__e> triggerNew) {
        this.triggerNew = triggerNew;
    }

    public void getApexJobs() {
        Set<Id> relevantAsyncApexJobIds = new Set<Id>();
        for (BatchApexStatusEvent__e evt : triggerNew) {
            relevantAsyncApexJobIds.add(evt.AsyncApexJobId__c);
        }

        relevantApexJobs = new Map<Id, AsyncApexJob>(
            [
                SELECT Id, Status, ExtendedStatus, TotalJobItems, JobItemsProcessed, NumberOfErrors, CreatedDate, CompletedDate
                FROM AsyncApexJob
                WHERE Id IN :relevantAsyncApexJobIds
            ]
        );
    }

    public void getParentLogs() {
        parentLogsById = new Map<Id, Batch_Job_Log__c>(
            [
                SELECT Id, Batch_Apex_Job__c, Batch_Job_Schedule__c, AsyncApexJobId__c, FailedBatches__c, SuccessfulBatches__c
                FROM Batch_Job_Log__c
                WHERE RecordTypeId = :RecordTypeCache.LOG_RECORD_TYPE_PARENT AND AsyncApexJobId__c IN :relevantApexJobs.keySet()
            ]
        );
        for (Batch_Job_Log__c log : parentLogsById.values()) {
            parentLogsByAsyncJobId.put(log.AsyncApexJobId__c, log);
        }
    }

    public Batch_Job_Log__c createChildLogRecord(BatchApexStatusEvent__e statusEvent) {
        Batch_Job_Log__c parentLog = parentLogsByAsyncJobId.get(statusEvent.AsyncApexJobId__c);
        Batch_Job_Log__c childLog = createChildLogFromEvent(statusEvent);
        childLog.Parent_Log__c = parentLog.Id;

        handleUpdatesForParentLogs(childLog);

        return childLog;
    }

    private Batch_Job_Log__c createChildLogFromEvent(BatchApexStatusEvent__e evt) {
        Batch_Job_Log__c childLog = new Batch_Job_Log__c(
            RecordTypeId = RecordTypeCache.LOG_RECORD_TYPE_CHILD,
            AsyncApexCallsLimit__c = evt.AsyncApexCallsLimit__c,
            AsyncApexCallsUsed__c = evt.AsyncApexCallsUsed__c,
            CPUTimeUsed__c = evt.CPUTimeUsed__c,
            CPUTimeLimit__c = evt.CPUTimeLimit__c,
            DMLRowsLimit__c = evt.DMLRowsLimit__c,
            DMLRowsUsed__c = evt.DMLRowsUsed__c,
            DMLStatementsLimit__c = evt.DMLStatementsLimit__c,
            DMLStatementsUsed__c = evt.DMLStatementsUsed__c,
            SOQLQueriesLimit__c = evt.SOQLQueriesLimit__c,
            SOQLQueriesUsed__c = evt.SOQLQueriesUsed__c,
            SOQLRowsLimit__c = evt.SOQLRowsLimit__c,
            SOQLRowsUsed__c = evt.SOQLRowsUsed__c,
            Context__c = evt.Context__c,
            Scope__c = evt.Scope__c,
            Execution_Result__c = evt.Message__c,
            Result__c = evt.Status__c,
            Timestamp__c = evt.Timestamp__c,
            ClassName__c = evt.ClassName__c,
            AsyncApexJobId__c = evt.AsyncApexJobId__c
        );
        return childLog;
    }

    private void handleUpdatesForParentLogs(Batch_Job_Log__c childLog) {
        Batch_Job_Log__c parentLog = parentLogsById.get(childLog.Parent_Log__c);
        switch on childLog.Result__c {
            when 'Error' {
                parentLog.FailedBatches__c += 1;
            }
            when 'Success' {
                parentLog.SuccessfulBatches__c += 1;
            }
        }

        if (childLog.Context__c == 'Finish') {
            String status;
            Boolean noBatches = parentLog.FailedBatches__c == 0 && parentLog.SuccessfulBatches__c == 0;
            Boolean hasSuccessfulBatches = parentLog.SuccessfulBatches__c > 0;
            Boolean hasFailedBatches = parentLog.FailedBatches__c > 0;
            if (noBatches || (hasSuccessfulBatches && !hasFailedBatches)) {
                status = 'Completed';
            }
            if (hasSuccessfulBatches && hasFailedBatches) {
                status = 'Completed with Errors';
            }
            if (hasFailedBatches && !hasSuccessfulBatches) {
                status = 'Failed';
            }
            parentLog.Completed_Date__c = DateTime.valueOf(childLog.Timestamp__c);
            parentLog.Result__c = status;
        }

        parentLogsById.put(parentLog.Id, parentLog);
    }
}