batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Group__c.field-meta.xml
<CustomField>
    <fullName>Batch_Group__c</fullName>
    <description>Group of batch jobs running together</description>
    <inlineHelpText>Group of batch jobs</inlineHelpText>
    <label>Batch Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Batch Apex job batch size, value between 1 to 2000.</description>
    <inlineHelpText>Value between 1 to 2000</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Job__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the Batch Apex job will be executed</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Job__c/recordTypes/Queueable.recordType-meta.xml
<RecordType>
    <fullName>Queueable</fullName>
    <active>true</active>
    <label>Queueable</label>
</RecordType>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/fields/Cron_Trigger_Id__c.field-meta.xml
<CustomField>
    <fullName>Cron_Trigger_Id__c</fullName>
    <description>Scheduled Job Cron Trigger Id</description>
    <inlineHelpText>Scheduled Job Cron Trigger Id</inlineHelpText>
    <label>Cron Trigger Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-scheduler-framework/main/batch-job-scheduler/classes/BatchJobScheduler.cls
global with sharing class BatchJobScheduler implements Schedulable {
    //Batch jobs in parallel run batches
    public ListMapContainer batchJobs;
    @TestVisible private Map<Integer,Boolean> isEnabledMap;
    @TestVisible private Integer index;

    global void execute(SchedulableContext sc) {
        run(sc.getTriggerId());
    }

    //Execute jobs from the beginning
    public void run(Id cronTriggerId) {
        batchJobs = loadActiveBatchJobs(cronTriggerId);
        executeJobs();
    }

    public void executeJobs(){
        if (batchJobs.getMap().keySet().isEmpty()) {
            return;
        }

        index = 1;
        List<Batch_Apex_Job__c> firstBatchGroup = getNextBatchJobs();
        if(!firstBatchGroup.isEmpty()){
            enqueueBatchJobs(batchJobs.get(String.valueOf(index)));
        }
    }

    //Execute jobs in next batch
    public void executeNextJob() {
        if (!hasPendingJobs(index)) {
            index++;
            List<Batch_Apex_Job__c> nextJobs = getNextBatchJobs();
            if(!nextJobs.isEmpty()){
                enqueueBatchJobs(nextJobs);
            }
        }
    }

    private List<Batch_Apex_Job__c> getNextBatchJobs(){
        List<Batch_Apex_Job__c> result = new List<Batch_Apex_Job__c>();
        index = getNextIndexWithEnabledJobs();
        if(index != null){
            result = batchJobs.get(String.valueOf(index));
        }
        return result;
    }

    public ListMapContainer loadActiveBatchJobs(Id cronTriggerId) {
        Batch_Job_Schedule__c schedule = [SELECT Id FROM Batch_Job_Schedule__c WHERE Cron_Trigger_Id__c = :cronTriggerId];
        return loadActiveBatchJobsById(schedule.Id);
    }
    //load active batch jobs from Batch_Apex_Job__c, sort by Batch No and Batch Sequence
    public ListMapContainer loadActiveBatchJobsById(Id scheduleId) {
        ListMapContainer batchJobListMap = new ListMapContainer(Batch_Apex_Job__c.SObjectType);
        isEnabledMap = new Map<Integer, Boolean>();

        for (Batch_Apex_Job__c baj : [
            SELECT
                Id,
                Name,
                Enabled__c,
                Batch_Class_Name__c,
                Batch_Size__c,
                Batch_Group__c,
                Batch_Job_Schedule__c,
                RecordType.DeveloperName
            FROM Batch_Apex_Job__c
            WHERE Batch_Job_Schedule__c = :scheduleId
            ORDER BY Batch_Group__c, CreatedDate
        ]) {
            if(!isEnabledMap.containsKey(Integer.valueOf(baj.Batch_Group__c))){
                isEnabledMap.put(Integer.valueOf(baj.Batch_Group__c), false);
            }
            if(baj.Enabled__c){
                batchJobListMap.addToMap(String.valueOf(baj.Batch_Group__c), baj);
                isEnabledMap.put(Integer.valueOf(baj.Batch_Group__c), true);
            }
        }
    
        return batchJobListMap;
    }

    private void enqueueBatchJobs(List<Batch_Apex_Job__c> apexJobs) {
        for (Batch_Apex_Job__c baj : apexJobs) {
            Id scheduleId = baj.Batch_JOb_Schedule__c;
            Id jobId = baj.Id;
            BatchJobBase job = getBatchJob(baj.Batch_Class_Name__c, baj.RecordType.DeveloperName);
            if (job != null && !Test.isRunningTest()) {
                job.batchJobScheduler = this;
                job.scheduleId = scheduleId;
                job.jobId = jobId;
                job.enqueue((Integer) baj.Batch_Size__c);
            }
        }
    }

    private Boolean hasPendingJobs(Integer checkedIndex) {
        Set<String> batchJobNames = new Set<String>();
        for (Batch_Apex_Job__c job : (List<Batch_Apex_Job__c>) batchJobs.get(String.valueOf(checkedIndex))) {
            batchJobNames.add(job.Batch_Class_Name__c);
        }

        List<AsyncApexJob> apexJobs = [
            SELECT Id, JobType, ApexClassId, Status, ApexClass.Name
            FROM AsyncApexJob
            WHERE
                JobType IN ('BatchApex', 'Queueable')
                AND Status IN ('Holding', 'Processing', 'Queued', 'Preparing')
                AND ApexClass.Name IN :batchJobNames
        ];
        //if any jobs are still running from the same batch
        return !apexJobs.isEmpty();
    }

    //Get batch job instance by batch job name
    private BatchJobBase getBatchJob(String jobName, String jobType) {
        BatchJobBase result = null;

        Type t = Type.forName(jobName);
        if (t != null) {
            result = (BatchJobBase) t.newInstance();
        } else {
            throw new TypeException('Cannot find batch job: ' + jobName);
        }
        //set ExecuteNextJob to true so it executes the next job when it finishes
        result.executeNextJob = true;
        result.jobType = jobType;
        return result;
    }

    private Integer getNextIndexWithEnabledJobs(){
        while(isEnabledMap.containsKey(index)){
            if(isEnabledMap.get(index)){
                return index;
            }
            index++;
        }
        return null;
    }
}