batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-scheduler-framework/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Batch Apex job batch size, value between 1 to 2000.</description>
    <inlineHelpText>Value between 1 to 2000</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/EnhancedLogging__c.field-meta.xml
<CustomField>
    <fullName>EnhancedLogging__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText
    >Enhanced Logging requires additional methods to be used and is recommended to be done with all Jobs of one schedule. Please refer to the README for more information.</inlineHelpText>
    <label>Enhanced Logging</label>
    <type>Checkbox</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-scheduler/classes/BatchOrchestrator.cls
public without sharing class BatchOrchestrator {
    public static void runBatchScheduleById(Id scheduleId) {
        BatchJobScheduler adhocSchedule = new BatchJobScheduler();
        adhocSchedule.batchJobs = adhocSchedule.loadActiveBatchJobsById(scheduleId);
        adhocSchedule.executeJobs();
    }

    public static void runBatchJob(Id batchJobId) {
        Batch_Apex_Job__c batchApexJob = [
            SELECT Batch_Class_Name__c, Batch_Job_Schedule__c, Batch_Size__c, RecordType.DeveloperName, EnhancedLogging__c
            FROM Batch_Apex_Job__c
            WHERE Id = :batchJobId
        ];
    }

    public static void runBatchJob(Batch_Apex_Job__c batchApexJob) {
        BatchJobBase batchJobToRun = (BatchJobBase) Type.forName(batchApexJob.Batch_Class_Name__c).newInstance();
        batchJobToRun.jobType = batchApexJob.RecordType.DeveloperName;
        batchJobToRun.executeNextJob = false;
        batchJobToRun.jobId = batchApexJob.Id;
        batchJobToRun.scheduleId = batchApexJob.Batch_Job_Schedule__c;
        batchJobToRun.className = batchApexJob.Batch_Class_Name__c;
        batchJobToRun.enhancedLoggingEnabled = batchApexJob.EnhancedLogging__c;

        batchJobToRun.enqueue(Integer.valueOf(batchApexJob.Batch_Size__c));
    }
}