batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class_Name__c</fullName>
    <description>Apex batch class name</description>
    <inlineHelpText>Batch Apex class name</inlineHelpText>
    <label>Batch Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/classes/BatchApexJobHandler.cls
public with sharing class BatchApexJobHandler extends TriggerHandlerExtension {
    public BatchApexJobHelper helper = BatchApexJobHelper.getInstance();

    public BatchApexJobHandler() {
        super();
    }

    public override void beforeInsert(SObject so) {
        Batch_Apex_Job__c apexJob = (Batch_Apex_Job__c) so;
        helper.verifyBatchJob(apexJob);
    }

    public override void beforeUpdate(SObject oldSO, SObject newSO) {
        Batch_Apex_Job__c apexJobNew = (Batch_Apex_Job__c) newSO;
        Batch_Apex_Job__c apexJobOld = (Batch_Apex_Job__c) oldSO;
        if (apexJobNew.Batch_Class_Name__c != apexJobOld.Batch_Class_Name__c) {
            helper.verifyBatchJob(apexJobNew);
        }
    }
}