batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/Batch_Apex_Job__c.object-meta.xml
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Apex_Job__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <description>Parent Batch Job Schedule</description>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>Batch Apex Jobs</relationshipLabel>
    <relationshipName>Batch_Apex_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/Batch_Job_Log__c.object-meta.xml
<CustomObject>
    <description>Apex Batch Job Log</description>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Apex_Job__c.field-meta.xml
<CustomField>
    <fullName>Batch_Apex_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Apex Job</label>
    <referenceTo>Batch_Apex_Job__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Name__c</fullName>
    <description>Apex Batch Job class name</description>
    <label>Batch Job Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batch_Job_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Job Schedule</label>
    <referenceTo>Batch_Job_Schedule__c</referenceTo>
    <relationshipLabel>All Batch Job Logs</relationshipLabel>
    <relationshipName>Batch_Job_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Batches_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batches_Processed__c</fullName>
    <label>Batches Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <description>Batch job completed time</description>
    <label>Completed Date</label>
    <type>DateTime</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Execution_Result__c.field-meta.xml
<CustomField>
    <fullName>Execution_Result__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Number_of_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Errors__c</fullName>
    <label>Number of Errors</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Schedule__c/Batch_Job_Schedule__c.object-meta.xml
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/BatchApexStatusEvent__e/BatchApexStatusEvent__e.object-meta.xml
<CustomObject>
    <label>Batch Apex Status Event</label>
    <pluralLabel>Batch Apex Status Events</pluralLabel>
</CustomObject>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/classes/BatchJobLogger.cls
/**
 * This class is part of the sfdx-batch-orchestrator package, released under the MIT license.
 *
 * @description       : Logger Class to bundle creation of Log Events
 * @author            : dschibster
 * @group             : Scheduler
 * @last modified on  : 2021-08-27
 * @last modified by  : dschibster
 **/

public with sharing class BatchJobLogger {
    public static void logStart(String className, Id asyncJobId, Id scheduleId, Id jobId) {
        writeParentLog(className, asyncJobId, scheduleId, jobId);
        BatchApexStatusEvent__e statusEvent = new BatchApexStatusEventBuilder()
            .withContext('Start')
            .withStatus('Batch Job Started')
            .withClassName(className)
            .withTimestamp(DateTime.now().getTime())
            .withJobId(asyncJobId)
            .withLimits()
            .getRecord();

        EventBus.publish(statusEvent);
    }

    public static void logFinish(Id asyncJobId) {
        BatchApexStatusEvent__e statusEvent = new BatchApexStatusEventBuilder()
            .withContext('Finish')
            .withStatus('Batch Job Finished')
            .withTimestamp(DateTime.now().getTime())
            .withJobId(asyncJobId)
            .withLimits()
            .getRecord();

        EventBus.publish(statusEvent);
    }

    public static void logExecute(List<SObject> chunkScope, Id asyncJobId, String status, String message) {
        BatchApexStatusEvent__e statusEvent = new BatchApexStatusEventBuilder()
            .withContext('Execute')
            .withStatus(status)
            .withMessage(message)
            .withScope(JSON.serializePretty(chunkScope).left(129999))
            .withTimestamp(DateTime.now().getTime())
            .withJobId(asyncJobId)
            .withLimits()
            .getRecord();

        EventBus.publish(statusEvent);
    }

    public static void writeParentLog(String className, Id asyncJobId, Id scheduleId, Id jobId) {
        Batch_Job_Log__c parentLog = new Batch_Job_Log__c(
            Batch_Job_Name__c = className,
            Batch_Apex_Job__c = jobId,
            Batch_Job_Schedule__c = scheduleId,
            AsyncApexJobId__c = asyncJobId,
            RecordTypeId = RecordTypeCache.LOG_RECORD_TYPE_PARENT
        );
        insert parentLog;
    }

    /**
     * Copyright (c) Ian Huang Salesforce
     *
     * Permission is hereby granted, free of charge, to any person obtaining a copy
     * of this software and associated documentation files (the "Software"), to deal
     * in the Software without restriction, including without limitation the rights
     * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
     * copies of the Software, and to permit persons to whom the Software is
     * furnished to do so, subject to the following conditions:
     * The above copyright notice and this permission notice shall be included in all
     * copies or substantial portions of the Software.
     *
     * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
     * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
     * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
     * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
     * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
     * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
     * OR OTHER DEALINGS IN THE SOFTWARE.
     */

    public static void logLegacy(String batchJobName, Id asyncJobId, Id scheduleId, Id jobId) {
        logLegacy(batchJobName, asyncJobId, '', scheduleId, jobId);
    }

    //Log batch job exection result
    public static void logLegacy(String batchJobName, Id asyncJobId, String summary, Id scheduleId, Id jobId) {
        AsyncApexJob job = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CompletedDate, CreatedBy.Email, ExtendedStatus
            FROM AsyncApexJob
            WHERE Id = :asyncJobId
        ];

        String executeResult = job.ExtendedStatus;

        // Create a batch job log record to notify the batch job execute result
        try {
            Batch_Job_Log__c bjl = new Batch_Job_Log__c(
                Batch_Job_Name__c = batchJobName,
                Batch_Apex_Job__c = jobId,
                Batch_Job_Schedule__c = scheduleId,
                Completed_Date__c = job.CompletedDate,
                Status__c = job.Status,
                Batches_Processed__c = job.JobItemsProcessed,
                Number_of_Errors__c = job.NumberOfErrors,
                Execution_Result__c = (String.isNotBlank(executeResult) ? executeResult : '') + (String.isNotBlank(summary) ? '\n' + summary : '')
            );
            insert bjl;
        } catch (Exception ex) {
            throw new DmlException('Failed to save batch job log: ' + ex.getMessage());
        }
    }
}