batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/Batch_Job_Log__c.object-meta.xml
<CustomObject>
    <description>Apex Batch Job Log</description>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

batch-orchestrator/main/batch-job-management/objects/Batch_Job_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Information</fullName>
                <label>ℹ️ Information</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>✔️ Success</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>⛔ Error</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <label>⛔ Failed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>✔️ Completed</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>⏳ Processing</label>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
                <label>⚠️ Completed with Errors</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

batch-orchestrator/test/batch-job-logging/classes/BatchJobLoggerTest.cls
/**
 * This class is part of the sfdx-batch-orchestrator package, released under the MIT license.
 *
 * @description       : Logger Test Class to test additional methods that aren't covered by BatchJobBaseTest
 * @author            : Dennis Grzyb
 * @group             :
 * @last modified on  : 2021-10-12
 * @last modified by  : Dennis Grzyb
 **/
@isTest
public with sharing class BatchJobLoggerTest {
    @IsTest
    static void shouldCreateEnhancedLogsForQueueable() {
        Test.startTest();
        BatchJobBase emptyQueueable = (BatchJobBase) new testQueueable();
        emptyQueueable.jobType = 'Queueable';
        emptyQueueable.className = 'testQueueable';
        emptyQueueable.enhancedLoggingEnabled = true;
        emptyQueueable.enqueue(null);
        Test.stopTest();
        Test.getEventBus().deliver();

        System.assertEquals(2, [SELECT COUNT() FROM Batch_Job_Log__c WHERE RecordTypeId = :RecordTypeCache.LOG_RECORD_TYPE_CHILD], 'No 3 log entries found');
        System.assertEquals(
            1,
            [SELECT COUNT() FROM Batch_Job_Log__c WHERE RecordTypeId = :RecordTypeCache.LOG_RECORD_TYPE_QUEUEABLE],
            'No parent log entry found'
        );
        Batch_Job_Log__c parentLog = [SELECT Id, Result__c FROM Batch_Job_Log__c WHERE RecordTypeId = :RecordTypeCache.LOG_RECORD_TYPE_QUEUEABLE LIMIT 1];
        System.assertEquals('Completed', parentLog.Result__c, 'No update to "completed" for Queuable Parent Log');
    }
}