batch-orchestrator/main/batch-job-management/objects/BatchApexStatusEvent__e/BatchApexStatusEvent__e.object-meta.xml
<CustomObject>
    <label>Batch Apex Status Event</label>
    <pluralLabel>Batch Apex Status Events</pluralLabel>
</CustomObject>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexCallsLimit__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexCallsUsed__c</fullName>
    <label>Async Apex Calls Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexCallsUsed__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexCallsLimit__c</fullName>
    <label>Async Apex Calls Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>Async Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/CPUTimeLimit__c.field-meta.xml
<CustomField>
    <fullName>CPUTimeLimit__c</fullName>
    <label>CPU Time Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/DMLRowsLimit__c.field-meta.xml
<CustomField>
    <fullName>DMLRowsLimit__c</fullName>
    <label>DML Rows Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/DMLStatementsLimit__c.field-meta.xml
<CustomField>
    <fullName>DMLStatementsLimit__c</fullName>
    <label>DML Statements Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/SObjectJSON__c.field-meta.xml
<CustomField>
    <fullName>SObjectJSON__c</fullName>
    <description
    >This field is used for the async creation of Parent Logs when in a Queuable. Can selectively be used for Batch Jobs too, however not necessary here. Used to ensure that Webservice Callouts don&apos;t run into &quot;uncommited work pending&quot; issues.</description>
    <label>SObject JSON</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/SOQLQueriesLimit__c.field-meta.xml
<CustomField>
    <fullName>SOQLQueriesLimit__c</fullName>
    <label>SOQL Queries Limit</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/SOQLQueriesUsed__c.field-meta.xml
<CustomField>
    <fullName>SOQLQueriesUsed__c</fullName>
    <label>SOQL Queries Used</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/objects/BatchApexStatusEvent__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

batch-orchestrator/main/batch-job-logging/objects/BatchApexStatusEvent__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

batch-orchestrator/main/batch-job-scheduler/classes/BatchApexStatusEventBuilder.cls
/**
 * This class is part of the sfdx-batch-orchestrator package, released under the MIT license.
 *
 * @description       : Builder class for Batch Apex Status Event
 * @author            : Dennis Grzyb
 * @group             : Scheduler
 * @last modified on  : 2021-10-12
 * @last modified by  : Dennis Grzyb
 **/

public with sharing class BatchApexStatusEventBuilder {
    BatchApexStatusEvent__e statusEvent;

    public BatchApexStatusEventBuilder() {
        this.statusEvent = new BatchApexstatusEvent__e();
    }

    public BatchApexStatusEventBuilder withJobId(Id jobId) {
        this.statusEvent.AsyncApexJobId__c = jobId;
        return this;
    }

    public BatchApexStatusEventBuilder withContext(String context) {
        this.statusEvent.Context__c = context;
        return this;
    }

    public BatchApexStatusEventBuilder withScope(String scope) {
        this.statusEvent.Scope__c = scope;
        return this;
    }

    public BatchApexStatusEventBuilder withStatus(String status) {
        this.statusEvent.Status__c = status;
        return this;
    }

    public BatchApexStatusEventBuilder withMessage(String message) {
        this.statusEvent.Message__c = message;
        return this;
    }

    public BatchApexStatusEventBuilder withTimestamp(Long timestamp) {
        this.statusEvent.Timestamp__c = timestamp;
        return this;
    }

    public BatchApexStatusEventBuilder withClassName(String className) {
        this.statusEvent.ClassName__c = className;
        return this;
    }

    public BatchApexStatusEventBuilder withLimits() {
        this.statusEvent.AsyncApexCallsLimit__c = Limits.getLimitAsyncCalls();
        this.statusEvent.AsyncApexCallsUsed__c = Limits.getAsyncCalls();
        this.statusEvent.CPUTimeLimit__c = Limits.getLimitCpuTime();
        this.statusEvent.CPUTimeUsed__c = Limits.getCpuTime();
        this.statusEvent.DMLRowsLimit__c = Limits.getLimitDMLRows();
        this.statusEvent.DMLRowsUsed__c = Limits.getDMLRows();
        this.statusEvent.DMLStatementsLimit__c = Limits.getLimitDmlStatements();
        this.statusEvent.DMLStatementsUsed__c = Limits.getDmlStatements();
        this.statusEvent.SOQLQueriesLimit__c = Limits.getLimitQueries();
        this.statusEvent.SOQLQueriesUsed__c = Limits.getQueries();
        this.statusEvent.SOQLRowsLimit__c = Limits.getLimitQueryRows();
        this.statusEvent.SOQLRowsUsed__c = Limits.getQueryRows();

        return this;
    }

    public BatchApexStatusEventBuilder withSObjectJSON(String sObjectJSON) {
        this.statusEvent.SObjectJSON__c = SObjectJSON;
        return this;
    }

    public BatchApexStatusEvent__e getRecord() {
        return this.statusEvent;
    }
}